---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cur8s/cert-manager.git
  ref:
    branch: main
  sparseCheckout:
    - releases/1.19
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: releases/1.19
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cert-manager
