---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cur8s/envoy-gateway.git
  ref:
    branch: main
  sparseCheckout:
    - releases/1.5
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-certs
  namespace: flux-system
spec:
  interval: 10m
  path: releases/1.5/certs
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: envoy-gateway
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 10m
  path: releases/1.5/crds/gateway-api
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: envoy-gateway
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crds
  namespace: flux-system
spec:
  interval: 10m
  path: releases/1.5/crds/envoy-gateway
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: envoy-gateway
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-deployment
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: envoy-gateway-crds
    - name: gateway-api-crds
    - name: envoy-gateway-certs
  path: releases/1.5/deployment
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: envoy-gateway
