---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/asaikali/hello-world
  ref:
    tag: v1.0.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  path: ./
  sourceRef:
    kind: OCIRepository
    name: hello-world
