---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cur8s/flux.git
  ref:
    branch: main
  sparseCheckout:
    - releases/2.7
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  path: ./releases/2.7
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux
